name: Chloe Corrigan's Portfolio
url: http://chloecorrigan.com
include: ['.htaccess']
sass:
  sass_dir: ./public/assets/_scss
  style: compressed
prose:
  siteurl: "http://chloecorrigan.com"
  media: 'public/assets'
  metadata:
    _layouts:
      - name: "about"
        field:
          label: "test"
          element: "text"
          value: "testing value"