name: Chloe Corrigan's Portfolio
url: http://chloecorrigan.com
include: ['.htaccess']
sass:
  sass_dir: ./public/assets/_scss
  style: compressed
prose:
  siteurl: "http://chloecorrigan.com"
  media: 'public/assets/images'
  metadata:
      - name: "description"
        field:
          label: "description"
          element: "text"
          value: "testing changed value"